server:
  port: 8080
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off
app:
  routes:
    restTemplate:
      requestMicroservice:
        tokenService:

        paymentService:
          addBalance: http://localhost:8078/paymentservice/addbalance
          getBalance: http://localhost:8078/paymentservice/getbalance
          deleteOrderByProductCode: http://localhost:8078/paymentservice/deleteorderbyproductcode
          getOrderList: http://localhost:8078/paymentservice/getorderlist

        userService:

        productService:
          createOrderList: http://localhost:8083/productservice/product/createorder
          getProductList: http://localhost:8083/productservice/product/productlist
          getCategoryList: http://localhost:8083/categoryservice/category/categorylist
          getProductListByCategoryName: http://localhost:8083/productservice/product/categorylistbycategoryname

        authService:
          registerUser: http://localhost:8081/auth/register
          authLogin: http://localhost:8081/auth/login
  presented:
    routescontroller:
      requestmapping:
        locked:
          indexServiceController: /index
        notlocked:
          authServiceController: /notlocked
          productServiceController: /notlocked
      locked:
        orderList:
          deleteOrderList: /deleteorderbyproductcode
          getOrderList: /getorderlist
          addOrderList: /product/buywithproductcode
        product:
          #buyWithProductCode: /product/buywithproductcode
        balance:
          addBalance: /balance/add
          getBalance: /balance/get
      notlocked:
        product:
          getProductList: /product/productlist
          getProductListByCategoryname: /product/productlistbycategoryname
        category:
          getCategoryList: /product/categorylist
        login:
          authUser: /login
          registerUser: /register
  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
  jwtCryptoSecret : sBnlg0BGosgPMQju
logging:
  level:
    org.springframework: DEBUG
