server:
  port: 8080
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off

client:
  feign:
    microServiceRegister-service:
      path: http://localhost:8090
      ready: /registerservice/ready
      stopped: /registerservice/stopped
      dashboard: /microservices/dashboard

    user-service:
      path: http://localhost:8082/user
      addBalance: /balance/addbalance
      getBalance: /balance/getbalance
      addAddressInfo: /address/add
      emailValidate: /activate
      activateSellerByAdmin: /activateseller
      getSellers: /seller/get

    payment-service:
      path: http://localhost:8078/paymentservice
      cart:
        buyItemsInCart: /buyitemsincart
        addItemInCart: /additemincart
        getItemListInCart: /getitemlistincart
        queryByTrackingNumber: /querybytrackingnumber

    auth-service:
      path: http://localhost:8081/auth
      login: /login
      register: /register
      changePassword: /changepassword
      logoutUser: /logout
      registerSellerRequest: /registerseller

    stock-service:
      path: http://localhost:8083/stock-service
      company:
        addCompany: /company/add

      category:
        listCategory: /category/list
        addCategory: /category/add
        updateCategory: /category/update

      product:
        getProduct: /product/get
        listProduct: /product/list
        addProduct: /product/add
        updateProduct: /product/update

app:
  routesController:
    controllers:
      secure:
        userServiceController: /user
        paymentServiceController: /payment
      notSecure:
        stockServiceController: /stock
        authServiceController: /auth

    requestMapping:
      secure:
        auth-service:
          changePassword: /changepassword
          logoutUser: /logout

        stock-service:
          addCategory: /category/add
          updateCategory: /category/update
          addProduct:  /product/add
          updateProduct: /product/update
          addCompany: /company/add

        payment-service:
          queryByTrackingNumber: /querybytrackingnumber
          addOrderList: /buywithproductcode
          deleteOrderList: /deleteorderbyproductcode
          getOrderList: /getorderlist
          buyItemsInCart: /buyitemsincart

        user-service:
          addBalance: /balance/add
          getBalance: /balance/get
          addAddressInfo: /address/add
          userActivate: /activate
          sellerActivateByAdmin: /seller/activate
          getSellers: /seller/get

      notSecure:
        stock-service:
          getProductByProductId: /product/getproduct
          getProductList: /product/list
          getCategoryList: /category/list

        auth-service:
          authUser: /login
          registerUser: /register
          registerSeller: /registerseller

  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
  jwtCryptoSecret: sBnlg0BGosgPMQju
logging:
  level:
    org.springframework: DEBUG
