server:
  port: 8080
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off
app:
  routes:
    restTemplate:
      requestMicroservice:
        tokenservice:

        paymentservice:

        userservice:

        productservice:

        authService:
          authLogin: http://localhost:8081/auth/login
  routescontroller:
    requestmapping:
      locked:
        indexServiceController: /index
      notlocked:
        authServiceController: /notlocked
        productServiceController: /notlocked
    locked:
      balance:
        addBalance: /balance/add
        getBalance: /balance/get
    notlocked:
      product:
        getProductList: /product/productlist
        getProductListByCategoryname: /product/productlistbycategoryname
      category:
        getCategoryList: /product/categorylist
      login:
        authUser: /login
        registerUser: /register
  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
  jwtCryptoSecret : sBnlg0BGosgPMQju
#logging:
#  level:
#    org.springframework: DEBUG
